pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'server/jade-digital-care-server/jade-digital-care-server.sln'
    vstsFeed: 'a28ae122-c4b7-4e1c-9df6-e3ec0c94ed7b'

- task: VSBuild@1
  displayName: 'Build Jade-Digital-Care Server'
  inputs:
    solution: 'server/jade-digital-care-server/jade-digital-care-server.sln'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*tests*.dll
     !**\*TestAdapter.dll
     !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)\server\jade-digital-care-server\Jade.Digital.Care.Server.Tests\bin\Debug'
    testFiltercriteria: 'TestCategory=Critical'
    diagnosticsEnabled: True

- task: ArchiveFiles@2
  displayName: 'Archive build artifacts'
  inputs:
    rootFolderOrFile: 'server/jade-digital-care-server/Jade.Digital.Care.Server/bin'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/jade-digital-care-server.$(Build.BuildNumber).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/'
    ArtifactName: 'jade-digital-care-server.$(Build.BuildNumber).zip'
